#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wcwidth
Version  : 0.1.7
Release  : 1
URL      : https://pypi.python.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz
Source0  : https://pypi.python.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz
Summary  : Measures number of Terminal column cells of wide-character codes
Group    : Development/Tools
License  : MIT
Requires: wcwidth-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
.. image:: https://img.shields.io/travis/jquast/wcwidth.svg
:target: https://travis-ci.org/jquast/wcwidth
:alt: Travis Continous Integration

%package python
Summary: python components for the wcwidth package.
Group: Default

%description python
python components for the wcwidth package.


%prep
%setup -q -n wcwidth-0.1.7

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485746908
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1485746908
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
